
<div class="row-fluid">
	<h2><?php echo $this->tlt("Advertiser campaigns").":"?></h2>
	<p><?php echo $this->tlt("Your credits").": ".$this->credits?></p>
</div>
<div class="row-fluid">
	<?php if(count($this->prizes)){?>
		<?php foreach($this->prizes as $prize) {?>
			<div class="row-fluid">
				<div class="span12 well">
					<div class="row-fluid">						
						<div class="span3">
							<a target="_blank" class="thumbnail" href="#">
								<img src="<?php echo $this->src($prize->images_url.'/150x150/'.@$prize->images[0]->file_name, '150x150', "owned-item.gif")?>"
								 alt="" 
								 />
							</a>
						</div>
						<div class="span9">
							<a href="/advertiser/index/prize/id/<?php echo $prize->id?>"><h3><?php echo $prize->name?></h3></a>
							<h4><?php echo $this->tlt("Credits cost").' :<b>'.$prize->price."</b>"?></h4>
							<h4><?php echo $this->tlt("Credits required").' :<b style="color:green">'.($prize->price - $this->credits > 0 ? $prize->price - $this->credits : "sufficient")."</b>"?></h4>
							<h4><?php echo $this->tlt("Remaining items no").' :<b>'.$prize->remaining_items."</b>"?></h4>
							<?php if($prize->price - $this->credits <= 0){?>
								<a class="btn btn-success"href="/publisher/index/buy/id/<?php echo $prize->id?>"><?php echo $this->tlt("Earn prize")?></a>
							<?php }?>
						</div>
					</div>
				</div>
			</div>
		<?php }?>
	<?php }else{?>
		<div class="alert alert-info"><?php echo $this->tlt("You have no prizes submitted")?></div>
	<?php }?>
</div>